error reporting

diff --git a/ci-vagrant/Vagrantfile b/ci-vagrant/Vagrantfile
--- a/ci-vagrant/Vagrantfile
+++ b/ci-vagrant/Vagrantfile
@@ -15,6 +15,13 @@ export BRANCH_CORE=$BRANCH_CORE
 export BRANCH_PLUGINS=$BRANCH_PLUGINS
 curl -L https://raw.githubusercontent.com/madcore-ai/core/$(echo $BRANCH_CORE)/ci-vagrant/ci-init-vagrant.sh | bash
 
+
+CODE=$?
+if [[ $CODE -ne 0 ]]; then
+    echo "INSTALLATION FAILED. GO FIGURE..."
+    exit -1
+fi
+
 GREEM='\033[1;31m'
 NC='\033[0m' # No Color
 printf "SUCCESS. JENKINS: ${GREEN} http://localhost:11111/blue ${NC}\n\n"
